### ISSUE TITLE
Crashes on use of custom fonts

### ISSUE THREAD

**Issue by 10by10pixel** [getwe/figlet4go#4]
Using [`small.flf`](http://www.figlet.org/fonts/small.flf) from the figlet website panics with output:
```
panic: runtime error: slice bounds out of range

goroutine 64 [running]:
panic(0x7fe1e0, 0xc82000a0d0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/getwe/figlet4go.(*fontManager).parseFontContent(0xc82034d520, 0xc82050d000, 0x2f94, 0x3194, 0x0, 0x0)
        /root/go/src/github.com/getwe/figlet4go/font.go:107 +0x3af
github.com/getwe/figlet4go.(*fontManager).loadDiskFont(0xc82034d520, 0x886e00, 0xb, 0x0, 0x0)
        /root/go/src/github.com/getwe/figlet4go/font.go:76 +0x222
github.com/getwe/figlet4go.(*fontManager).getFont(0xc82034d520, 0x886e00, 0xb, 0x9, 0x0, 0x0)
        /root/go/src/github.com/getwe/figlet4go/font.go:119 +0x99
github.com/getwe/figlet4go.(*AsciiRender).render(0xc820024238, 0x880bf8, 0x4, 0xc820047b50, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/getwe/figlet4go/render.go:71 +0x75
github.com/getwe/figlet4go.(*AsciiRender).RenderOpts(0xc820024238, 0x880bf8, 0x4, 0xc820047b50, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/getwe/figlet4go/render.go:45 +0x5a
main.messageCreate(0xc8200b8000, 0xc820024230)
        /root/test/main.go:93 +0x97c
reflect.Value.call(0x766dc0, 0x942f38, 0x13, 0x87ff00, 0x4, 0xc8202ecb10, 0x2, 0x2, 0x0, 0x0, ...)
        /usr/lib/go-1.6/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x766dc0, 0x942f38, 0x13, 0xc8202ecb10, 0x2, 0x2, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/reflect/value.go:303 +0xb1
created by github.com/bwmarrin/discordgo.(*Session).handle
        /root/go/src/github.com/bwmarrin/discordgo/discord.go:216 +0x575
exit status 2
```

**Comment by weberhong** [comment]
Thank you！Bug is fixed on [bc879344e874dd110753d17083a2a7acf3136683](https://github.com/getwe/figlet4go/commit/bc879344e874dd110753d17083a2a7acf3136683)
